import { StyleSheet } from 'react-native';

import { INK, MUTED, PAPER, monoFont, serifFont } from '../authStyles';

const RUST = '#cf4b2f';
const LINE = '#d9d1c1';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: PAPER,
    flex: 1,
    position: 'relative',
  },
  scrollContent: {
    paddingTop: 10,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 102,
  },
  locationRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  plusMark: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  deliverText: {
    color: MUTED,
    fontFamily: monoFont,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 3,
    lineHeight: 14,
  },
  locationText: {
    color: INK,
    fontFamily: 'serif',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 31,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  iconButton: {
    alignItems: 'center',
    borderColor: '#aaa69e',
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  headerIcon: {
    height: 19,
    width: 19,
  },
  headerBadge: {
    alignItems: 'center',
    backgroundColor: RUST,
    borderRadius: 12,
    height: 24,
    justifyContent: 'center',
    position: 'absolute',
    right: -7,
    top: -6,
    width: 24,
  },
  badgeText: {
    color: '#fff9ee',
    fontFamily: monoFont,
    fontSize: 12,
    fontWeight: '900',
  },
  hero: {
    borderColor: '#111111',
    borderRadius: 6,
    borderWidth: 2,
    height: 152,
    overflow: 'hidden',
    position: 'relative',
  },
  heroImage: {
    height: '100%',
    width: '100%',
  },
  heroOverlay: {
    backgroundColor: 'rgba(8, 24, 52, 0.34)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '58%',
  },
  freshPill: {
    backgroundColor: RUST,
    borderRadius: 4,
    color: '#fff9ee',
    fontFamily: monoFont,
    fontSize: 11,
    fontWeight: '900',
    left: 34,
    letterSpacing: 3,
    lineHeight: 24,
    paddingHorizontal: 12,
    position: 'absolute',
    top: 28,
  },
  heroKicker: {
    color: '#f5d47b',
    fontFamily: monoFont,
    fontSize: 12,
    fontWeight: '700',
    left: 34,
    letterSpacing: 5,
    position: 'absolute',
    top: 76,
  },
  heroTitle: {
    color: '#fff9ee',
    fontFamily: 'serif',
    fontSize: 32,
    fontWeight: '800',
    left: 34,
    lineHeight: 37,
    position: 'absolute',
    top: 96,
  },
  heroSubtitle: {
    color: '#fff9ee',
    fontFamily: serifFont,
    fontSize: 14,
    fontWeight: '700',
    left: 34,
    position: 'absolute',
    top: 131,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 22,
  },
  sectionTitle: {
    color: INK,
    fontFamily: monoFont,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 3,
  },
  actionLink: {
    color: RUST,
    fontFamily: monoFont,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 3,
  },
  sectionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 14,
  },
  sectionCard: {
    borderColor: LINE,
    borderRadius: 4,
    borderWidth: 1,
    height: 62,
    overflow: 'hidden',
    position: 'relative',
  },
  sectionImage: {
    height: '100%',
    width: '100%',
  },
  cardShade: {
    backgroundColor: 'rgba(11, 27, 58, 0.32)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  sectionNumeral: {
    color: '#fff9ee',
    fontFamily: monoFont,
    fontSize: 9,
    fontWeight: '900',
    left: 24,
    letterSpacing: 3,
    position: 'absolute',
    top: 9,
  },
  sectionName: {
    color: '#fff9ee',
    fontFamily: 'serif',
    fontSize: 22,
    fontWeight: '800',
    left: 24,
    lineHeight: 26,
    position: 'absolute',
    top: 28,
  },
  specimens: {
    color: '#e8e1d4',
    fontFamily: monoFont,
    fontSize: 9,
    fontWeight: '700',
    left: 24,
    letterSpacing: 3,
    position: 'absolute',
    top: 49,
  },
  picksHeader: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 22,
  },
  picksScript: {
    color: MUTED,
    fontFamily: serifFont,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 2,
  },
  productsRow: {
    gap: 25,
    paddingTop: 14,
  },
  productCard: {
    backgroundColor: PAPER,
    borderColor: LINE,
    borderRadius: 4,
    borderWidth: 1,
    overflow: 'hidden',
  },
  productImageWrap: {
    height: 112,
    position: 'relative',
  },
  productImage: {
    height: '100%',
    width: '100%',
  },
  productFresh: {
    backgroundColor: '#fff9ee',
    borderColor: '#a71d22',
    borderRadius: 3,
    borderWidth: 2,
    color: '#9d1c20',
    fontFamily: monoFont,
    fontSize: 10,
    fontWeight: '900',
    left: 16,
    letterSpacing: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    position: 'absolute',
    top: 16,
    transform: [{ rotate: '-3deg' }],
  },
  productInfo: {
    paddingHorizontal: 11,
    paddingVertical: 10,
  },
  productName: {
    color: INK,
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  productMeta: {
    color: MUTED,
    fontFamily: monoFont,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 3,
    marginTop: 4,
  },
  priceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  price: {
    color: INK,
    fontFamily: 'serif',
    fontSize: 22,
    fontWeight: '800',
  },
  addButton: {
    alignItems: 'center',
    borderColor: RUST,
    borderRadius: 6,
    borderWidth: 2,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  addText: {
    color: RUST,
    fontFamily: monoFont,
    fontSize: 20,
    lineHeight: 22,
  },
  bottomNav: {
    alignSelf: 'center',
    backgroundColor: PAPER,
    borderTopColor: '#222222',
    borderTopWidth: 3,
    bottom: 0,
    flexDirection: 'row',
    height: 104,
    justifyContent: 'space-around',
    left: 0,
    position: 'absolute',
    right: 0,
    width: '100%',
  },
  navItem: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  navIcon: {
    height: 24,
    width: 24,
  },
  navBadge: {
    alignItems: 'center',
    backgroundColor: RUST,
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: -13,
    top: -6,
    width: 30,
  },
  navBadgeText: {
    color: '#fff9ee',
    fontFamily: monoFont,
    fontSize: 11,
    fontWeight: '900',
  },
  navLabel: {
    color: MUTED,
    fontFamily: monoFont,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 3,
    marginTop: 12,
  },
  navLabelActive: {
    color: RUST,
  },
});
